config/routes.rb
Somethingchic::Application.routes.draw do

  resources :blogs, :comments, :users, :user_sessions, :homes, :galleries, :request_information, :users, :user_sessions, :gallery_sections, :services, :events
  
  root :to => 'homes#index'
  
  match 'create_comment/:id' => 'blogs#create_comment', :as => :comment_create
  match 'comments/:id/new_comment' => 'comments#new_comment', :as => :comment
  match 'blogs/:id/show-:title.html' => 'blogs#show', :as => :blog_view
  match 'blogs' => 'blogs#index', :as => :blog_home
  match 'events/:id/show-:title.html' => 'events#show', :as => :event_view
  match 'events' => 'events#index', :as => :event_home
  match 'services' => 'services#index', :as => :service_home
  match 'blog_categories/:id/:title-index.html' => 'blog_categories#show', :as => :blogs_by_name
  match 'galleries/:id/:title-index.html' => 'galleries#index', :as => :gallery_view
  match 'gallery_sections' => 'gallery_sections#index', :as => :gallery_section_index
  match 'galleries/:id/:title-view.html' => 'galleries#show', :as => :picture_view
  match 'create_gallery_comment/:id' => 'galleries#create_comment', :as => :picture_comment
  match 'home' => 'homes#index', :as => :home
  match 'comment_create_events' => 'events#create_comment', :as => :comment_create_events
    
  match 'request_information' => 'request_information#index', :as => :request 
  match 'sendmail' => 'request_information#sendmail'

  match '/manager/index_home' => 'manager#index_home', :as => :manager_index_home
  match '/manager/:id/update_home' => 'manager#update_home', :as => :manager_update_home
  match '/manager/create_home' => 'manager#create_home', :as => :manager_create_home
  match '/manager/:id/edit_home' => 'manager#edit_home', :as => :manager_edit_home
  match '/manager/new_home' => 'manager#new_home', :as => :manager_new_home
  match '/manager/:id/destroy_home' => 'manager#destroy_home', :as => :manager_destroy_home

  match '/manager/index_blog' => 'manager#index_blog', :as => :manager_index_blog
  match '/manager/:id/update_blog' => 'manager#update_blog', :as => :manager_update_blog
  match '/manager/create_blog' => 'manager#create_blog', :as => :manager_create_blog
  match '/manager/:id/edit_blog' => 'manager#edit_blog', :as => :manager_edit_blog
  match '/manager/new_blog' => 'manager#new_blog', :as => :manager_new_blog
  match '/manager/:id/destroy_blog' => 'manager#destroy_blog', :as => :manager_destroy_blog
  
  match '/manager/index_gallery' => 'manager#index_gallery', :as => :manager_index_gallery
  match '/manager/:id/update_gallery' => 'manager#update_gallery', :as => :manager_update_gallery
  match '/manager/create_gallery' => 'manager#create_gallery', :as => :manager_create_gallery
  match '/manager/:id/edit_gallery' => 'manager#edit_gallery', :as => :manager_edit_gallery
  match '/manager/new_gallery' => 'manager#new_gallery', :as => :manager_new_gallery
  match '/manager/:id/destroy_gallery' => 'manager#destroy_gallery', :as => :manager_destroy_gallery
  
  match '/manager/index_gallery_sections' => 'manager#index_gallery_sections', :as => :manager_index_gallery_sections
  match '/manager/:id/update_gallery_sections' => 'manager#update_gallery_sections', :as => :manager_update_gallery_sections
  match '/manager/create_gallery_sections' => 'manager#create_gallery_sections', :as => :manager_create_gallery_sections
  match '/manager/:id/edit_gallery_sections' => 'manager#edit_gallery_sections', :as => :manager_edit_gallery_sections
  match '/manager/new_gallery_sections' => 'manager#new_gallery_sections', :as => :manager_new_gallery_sections
  match '/manager/:id/destroy_gallery_sections' => 'manager#destroy_gallery_sections', :as => :manager_destroy_gallery_sections
  
  match '/manager/index_blog_categories' => 'manager#index_blog_categories', :as => :manager_index_blog_categories
  match '/manager/:id/update_blog_categories' => 'manager#update_blog_categories', :as => :manager_update_blog_categories
  match '/manager/create_blog_categories' => 'manager#create_blog_categories', :as => :manager_create_blog_categories
  match '/manager/:id/edit_blog_categories' => 'manager#edit_blog_categories', :as => :manager_edit_blog_categories
  match '/manager/new_blog_categories' => 'manager#new_blog_categories', :as => :manager_new_blog_categories
  match '/manager/:id/destroy_blog_categories' => 'manager#destroy_blog_categories', :as => :manager_destroy_blog_categories
  
  match '/manager/index_events' => 'manager#index_events', :as => :manager_index_events
  match '/manager/:id/update_events' => 'manager#update_events', :as => :manager_update_events
  match '/manager/create_events' => 'manager#create_events', :as => :manager_create_events
  match '/manager/:id/edit_events' => 'manager#edit_events', :as => :manager_edit_events
  match '/manager/new_events' => 'manager#new_events', :as => :manager_new_events
  match '/manager/:id/destroy_events' => 'manager#destroy_events', :as => :manager_destroy_events
  
  match '/manager/index_services' => 'manager#index_services', :as => :manager_index_services
  match '/manager/:id/update_services' => 'manager#update_services', :as => :manager_update_services
  match '/manager/create_services' => 'manager#create_services', :as => :manager_create_services
  match '/manager/:id/edit_services' => 'manager#edit_services', :as => :manager_edit_services
  match '/manager/new_services' => 'manager#new_services', :as => :manager_new_services
  match '/manager/:id/destroy_services' => 'manager#destroy_services', :as => :manager_destroy_services
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'register' => 'users#new', :as => :register
  
  match 'comments/:id/remove_comment_blog/:blog_id' => 'comments#remove_comment_blog', :as => :remove_comment_blog
  match 'comments/:id/remove_comment_gallery/:blog_id' => 'comments#remove_comment_gallery', :as => :remove_comment_gallery
  

end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController

  def index_home
    @homes = Home.all
    @homes = @homes.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new_home
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit_home
    @home = Home.find(params[:id])
  end

  def create_home
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to(:home, :notice => 'Homepage image was successfully added.') }
      else
        format.html { render :action => "new_home" }
        flash[:error] = 'There was an error adding image.'
      end
    end
  end

  def update_home
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to( :manager_index_home, :notice => 'Image was successfully updated.') }
      else
        format.html { render :action => "edit_home" }
        flash[:error] = 'There was an error updating image.'
      end
    end
  end

  def destroy_home
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to( manager_index_home_url) }
      flash[:notice] = 'Image was successfully deleted.'
    end
  end
  
  def index_blog
    @blogs = Blog.all
    @blogs = @blogs.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new_blog
    @blog = Blog.new
    @blog_categories = BlogCategory.all

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit_blog
    @blog = Blog.find(params[:id])
    @blog_categories = BlogCategory.all
  end

  def create_blog
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to(:manager_index_blog, :notice => 'Blog was successfully created.') }
      else
        format.html { render :action => "new_blog" }
        flash[:error] = 'There was a problem creating blog entry.'
      end
    end
  end

  def update_blog
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to(:manager_index_blog, :notice => 'Blog was successfully updated.') }
      else
        format.html { render :action => "edit_blog" }
        flash[:error] = 'There was a problem updating blog entry.'
      end
    end
  end

  def destroy_blog
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to(:manager_index_blog) }
      flash[:notice] = 'Blog entry was successfully deleted.'
    end
  end

  #*******************
  #**** Gallery ******
  #*******************

  def index_gallery
    @galleries = Gallery.find(:all, :order => "created_at desc")
    @galleries = @galleries.paginate(:page => params[:page], :per_page => 30)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new_gallery
    @gallery = Gallery.new
    @gallery_sections = GallerySection.all

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit_gallery
    @gallery = Gallery.find(params[:id])
    @gallery_sections = GallerySection.all
  end

  def create_gallery
    @gallery = Gallery.new(params[:gallery])
    @gallery_sections = GallerySection.all

    respond_to do |format|
      if @gallery.save 
        format.html { redirect_to(:manager_index_gallery, :notice => 'Image was successfully add to the gallery.') }
      else
        format.html { render :action => "new_gallery" }
        flash[:error] = 'There was an issue add image to gallery.'
      end
    end
  end

  def update_gallery
    @gallery = Gallery.find(params[:id])
    @gallery_sections = GallerySection.all

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to(:manager_index_gallery, :notice => 'Gallery was successfully updated.') }
      else 
        format.html { render :action => "edit_gallery" }
        flash[:error] = 'There was an issue add image to gallery.'
      end
    end
  end

  def destroy_gallery
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to(:manager_index_gallery) }
      flash[:notice] = 'Image was successfully deleted.'
    end
  end

  #*******************
  #* Gallery Section *
  #*******************

  def index_gallery_sections
    @gallery_sections = GallerySection.all
    @gallery_sections = @gallery_sections.paginate(:page => params[:page], :per_page => 8)

    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def new_gallery_sections
    @gallery_section = GallerySection.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit_gallery_sections
    @gallery_section = GallerySection.find(params[:id])
  end

  def create_gallery_sections
    @gallery_section = GallerySection.new(params[:gallery_section])

    respond_to do |format|
      if @gallery_section.save
        format.html { redirect_to(:manager_index_gallery_sections, :notice => 'Gallery section was successfully created.') }
      else
        format.html { render :action => "new_gallery_sections" }
      end
    end
  end

  def update_gallery_sections
    @gallery_section = GallerySection.find(params[:id])

    respond_to do |format|
      if @gallery_section.update_attributes(params[:gallery_section])
        format.html { redirect_to(:manager_index_gallery_sections, :notice => 'Gallery section was successfully updated.') }
      else
        format.html { render :action => "edit_gallery_sections" }
        flash[:notice] = 'Gallery was successfully deleted.'
      end
    end
  end
  
  def destroy_gallery_sections
    @gallery_section = GallerySection.find(params[:id])
    @gallery_section.destroy

    respond_to do |format|
      format.html { redirect_to(:manager_index_gallery_sections) }
      flash[:notice] = 'Gallery was successfully deleted.'
    end
  end
  
  #*******************
  #* Blog Categories *
  #*******************

  def index_blog_categories
    @blog_categories = BlogCategory.all
    @blog_categories = @blog_categories.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new_blog_categories
    @blog_category = BlogCategory.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit_blog_categories
    @blog_category = BlogCategory.find(params[:id])
  end

  def create_blog_categories
    @blog_category = BlogCategory.new(params[:blog_category])

    respond_to do |format|
      if @blog_category.save
      	format.html { redirect_to(:manager_index_blog_categories, :notice => 'Blog category was successfully created.') }
      else
      	format.html { render :action => "new_blog_categories" }
      end
    end
  end

  def update_blog_categories
    @blog_category = BlogCategory.find(params[:id])

    respond_to do |format|
      if @blog_category.update_attributes(params[:blog_category])
      	format.html { redirect_to(:manager_index_blog_categories, :notice => 'Blog category was successfully updated.') }
      else
        format.html { render :action => "edit_blog_categories" }
        flash[:notice] = 'Blog category was successfully deleted.'
      end
    end
  end

  def destroy_blog_categories
    @blog_category = BlogCategory.find(params[:id])
    @blog_category.destroy

    respond_to do |format|
      format.html { redirect_to(:manager_index_blog_categories) }
      flash[:notice] = 'Blog category was successfully deleted.'
    end
  end
  
  #*******************
  #**** Services *****
  #*******************
 
  def index_services
    @services = Service.all
    @services = @services.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def new_services
    @service = Service.new
    @galleries = Gallery.find(:all, :order => "gallery_id desc")

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit_services
    @service = Service.find(params[:id])
    @galleries = Gallery.find(:all, :order => "gallery_id desc")
  end

  def create_services
    @service = Service.new(params[:service])
    @galleries = Gallery.find(:all, :order => "gallery_id desc")

    respond_to do |format|
      if @service.save
      	format.html { redirect_to(:manager_index_services, :notice => 'Service was successfully added.') }
      else
      	format.html { render :action => "new_services" }
      end
    end
  end

  def update_services
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to(:manager_index_services, :notice => 'Service was successfully updated.') }
      else
        format.html { render :action => "edit_services" }
        flash[:notice] = 'Service was successfully deleted.'
      end
    end
  end

  def destroy_services
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to(:manager_index_services) }
      flash[:notice] = 'Service was successfully deleted.'
    end
  end
    
  #*******************
  #***** Events ******
  #*******************
 
  def index_events
    @events = Event.all
    @events = @events.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def new_events
    @event = Event.new
    @gallery_sections = GallerySection.all
    @blog_categories = BlogCategory.all
    @galleries = Gallery.find(:all, :order => "gallery_id desc")

    respond_to do |format|
      format.html # new.html.erb

app/helpers/manager_helper.rb
module ManagerHelper
end

app/views/manager/edit_blog_categories.html.erb
<h1>Editing blog category</h1>

<%= form_for @blog_category, :url => manager_update_blog_categories_path( @blog_category ) do |f| %>
  <% if @blog_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_category.errors.count, "error") %> prohibited this blog_category from being saved:</h2>

      <ul>
      <% @blog_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>


<%= link_to 'Delete', manager_destroy_blog_categories_path(@blog_category.id)%> |
<%= link_to 'Back', manager_index_blog_categories_path %>

app/views/manager/edit_gallery.html.erb
<h1>Edit gallery image</h1>
 
<%= form_for @gallery, :url => manager_update_gallery_path( @home ) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field pad10">
  <%= image_tag(@gallery.photo.url(:thumb)) %>
  </div>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
   <div class="field">
  	<select name="gallery[gallery_id]">
  		<% @gallery_sections.each do |gallery| %>
			<option value="<%= gallery.id %>"  <% if gallery.id == @gallery.gallery_id %>selected<% end %>><%= gallery.title %></option>
		<% end %>
	</select>
  </div> 
  <div class="actions">
    <%= f.submit "Update"%>
  </div>
<% end %>

<%= link_to 'Delete', manager_destroy_gallery_path(@gallery) %> |
<%= link_to 'Back', manager_index_gallery_path %>

app/views/manager/edit_home.html.erb
<h1>Update homepage image</h1>

<%= form_for @home, :url => manager_update_home_path( @home ) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field pad10">
  	<%= image_tag(@home.photo.url(:home), :width => "90%") %>
  </div>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <!-- div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div -->
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to 'Delete', manager_destroy_home_path(@home) %> |
<%= link_to 'Back', manager_index_home_path %>

app/views/manager/edit_services.html.erb
<script type="text/javascript">
$(document).ready(function() { 
    $("#image").change(function() { 
        var src = $(this).val(); 
 
        $("#imagePreview").html(src ? "<img src='" + src + "'>" : ""); 
    }); 
}); 
</script>

<h1>Edit service</h1>

<%= form_for @service, :url => manager_update_services_path( @service ) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "80x40" %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label "Select an image" %><br />
    <select name="service[image_url]" id="image">
  		<% @galleries.each do |gallery| %>
			<option value="<%= gallery.photo.url(:thumb) %>"  <% if gallery.photo.url(:thumb) == @service.image_url %>selected<% end %>><%= gallery.title %></option>
		<% end %>
	</select>    
  </div>
  <div id="imagePreview"> 
  	<img src="<%= @service.image_url %>"/>
  </div> 
  <div class="actions">
    <%= f.submit "Update service"%>
  </div>
<% end %>


<%= link_to 'Delete', manager_destroy_services_path(@service) %> |
<%= link_to 'Back', manager_index_services_path %>

app/views/manager/index_blog.html.erb
<h1>Manage Blogs</h1>
<div class="left clear marb20"><%= link_to "Create a new blog", manager_new_blog_path %></div>

<table cellspacing="10" width="700px">
  <tr>
    <th>Title</th>
    <th>Date Posted</th>
    <th>Blog Category</th>
    <th></th>
    <th></th>
  </tr>
	<% @blogs.each do |blog| %>
	  <tr>
	    <td><%= blog.title %></td>
	    <td><%= blog.created_at.strftime("%B %d, %Y") %></td>
	    <td><%= get_blog_category :blog_category_id => blog.category_id %></td>
	    <td><%= link_to "Edit", manager_edit_blog_path(blog.id) %></td>
	    <td><%= link_to "Delete", manager_destroy_blog_path(blog.id) %></td>
	  </tr>			
	<% end %>
</table>

<div id="paginate-style">
	<%= will_paginate @blogs %>
</div>
<div class="clear"></div>

app/views/manager/index_blog_categories.html.erb
<h1>Blog Categories</h1>
<div class="left clear marb20"><%= link_to "New Blog category", manager_new_blog_categories_path %></div>

<table cellspacing="10" width="700px">
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Date Created</th>
    <th></th>
    <th></th>
  </tr>

<% @blog_categories.each do |blog_category| %>
  <tr>
    <td><%= blog_category.title %></td>
    <td><%= truncate( blog_category.body, :length => 50) %></td>
    <td>
    	<%= blog_category.created_at.strftime("%B %d, %Y") %>
    </td>
    <td><%= link_to "Edit", manager_edit_blog_categories_path(blog_category.id) %></td>
    <td><%= link_to "Delete", manager_destroy_blog_categories_path(blog_category.id) %></td>
  </tr>
<% end %>
</table>

<div id="paginate-style">
	<%= will_paginate @blog_categories %>
</div>
<div class="clear"></div>

app/views/manager/index_events.html.erb
<style>
	#preview img { width:100%; }
	#preview { width:175px; }
</style>

<h1>Manage Events</h1>
<div class="left clear marb20"><%= link_to "Add a new event", manager_new_events_path %></div>

<table cellspacing="10" width="700px">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Blog category</th>
    <th>Gallery section</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= link_to event.title, event.price, :class =>"preview" %></td>
    <td><%= truncate( event.description, :length => 20 ) %></td>
    <td><%= get_blog_category :blog_category_id => event.blog_category_id %></td>
    <td><%= get_gallery_section :category_id => event.gallery_section_id %></td>
    <td><%= event.created_at.strftime("%B %d, %Y") %></td>
    <td><%= link_to 'Edit', manager_edit_events_path(event.id) %></td>
    <td><%= link_to 'Delete', manager_destroy_events_path(event.id) %></td>
  </tr>
<% end %>
</table>

<div id="paginate-style">
	<%= will_paginate @events %>
</div>
<div class="clear"></div>

app/views/manager/index_gallery_sections.html.erb
<h1>Manage Gallery Sections</h1>
<div class="left clear marb20"><%= link_to "Create a new gallery section", manager_new_gallery_sections_path %></div>
		   	
<table cellspacing="10" width="700px">
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
  </tr>
	<% @gallery_sections.each do |gallery| %>
		<tr>
	    	<td><%= link_to gallery.title, gallery.photo.url(:thumb), :class =>"preview" %></td>
	    	<td><%= gallery.body %></td>
	    	<td><%= link_to 'Edit', manager_edit_gallery_sections_path(gallery.id) %></td>
	    	<td><%= link_to 'Delete', manager_destroy_gallery_sections_path(gallery.id) %></td>
	    </tr>
	<% end %>
</table>
	
<div id="paginate-style">
	<%= will_paginate @gallery_sections %>
</div>
<div class="clear"></div>

app/views/manager/index_home.html.erb
<style>
	#preview img { width:100%; }
	#preview { width:500px; }
</style>

<h1>Manage Home Page Images</h1>
<div class="left clear marb20"><%= link_to "Add new home page image", manager_new_home_path %></div>

<table cellspacing="10" width="700px">
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Date Created</th>
    <th></th>
    <th></th>
  </tr>
	<% @homes.each do |home| %>
	<tr>
    	<td><%= link_to home.title, home.photo.url(:home), :class =>"preview" %></td>
    	<td><%= truncate( home.body, :length => 50 ) %></td>
    	<td>
    		<%= home.created_at.strftime("%B %d, %Y") %>
    	</td>
    	<td><%= link_to 'Edit', manager_edit_home_path(home.id) %></td>
    	<td><%= link_to 'Delete', manager_destroy_home_path(home.id) %></td>
    </tr>
		
	<% end %>
	
</table>
<div id="paginate-style">
	<%= will_paginate @homes %>
</div>
<div class="clear"></div>

app/views/manager/new_events.html.erb
<script type="text/javascript">
$(document).ready(function() { 
    $("#image").change(function() { 
        var src = $(this).val(); 
 
        $("#imagePreview").html(src ? "<img src='" + src + "'>" : ""); 
    }); 
}); 
</script>

<h1>New event</h1>

<%= form_for @event, :url => manager_create_events_path do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "80x40" %>
  </div>
  <div class="field">
    <%= f.label "Select event image" %><br />
    <select name="event[price]" id="image">
  		<option value="">-- Select Image --</option>
  		<% @galleries.each do |gallery| %>
			<option value="<%= gallery.photo.url(:thumb) %>"><%= gallery.title %></option>
		<% end %>
	</select>
  </div>
  <div id="imagePreview"> 
  	displays image here 
  </div> 
  <div class="field">
    <%= f.label "Select blog category" %><br />
    <select name="event[blog_category_id]">
  		<option value="">-- Select Blog Category --</option>
		<% @blog_categories.each do |bc| %>
			<option value="<%= bc.id %>"><%= bc.title %></option>
		<% end %>
	</select>
  </div>
  <div class="field">
    <%= f.label "Select gallery section" %><br />
    <select name="event[gallery_section_id]">
  		<option value="">-- Select Gallery Section --</option>
  		<% @gallery_sections.each do |gs| %>
			<option value="<%= gs.id %>"><%= gs.title %></option>
		<% end %>
	</select>
  </div>
  <div class="actions">
    <%= f.submit "Create Event" %>
  </div>
<% end %>

<%= link_to 'Back', manager_index_events_path %>

app/views/manager/show_home.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @home.title %>
</p>

<p>
  <b>Body:</b>
  <%= @home.body %>
</p>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>