config/routes.rb
Somethingchic::Application.routes.draw do

  resources :blogs, :comments, :users, :user_sessions, :homes, :galleries, :request_information, :users, :user_sessions, :gallery_sections, :services, :events
  
  root :to => 'homes#index'
  
  match 'create_comment/:id' => 'blogs#create_comment', :as => :comment_create
  match 'comments/:id/new_comment' => 'comments#new_comment', :as => :comment
  match 'blogs/:id/show-:title.html' => 'blogs#show', :as => :blog_view
  match 'blogs' => 'blogs#index', :as => :blog_home
  match 'events/:id/show-:title.html' => 'events#show', :as => :event_view
  match 'events' => 'events#index', :as => :event_home
  match 'services' => 'services#index', :as => :service_home
  match 'blog_categories/:id/:title-index.html' => 'blog_categories#show', :as => :blogs_by_name
  match 'galleries/:id/:title-index.html' => 'galleries#index', :as => :gallery_view
  match 'gallery_sections' => 'gallery_sections#index', :as => :gallery_section_index
  match 'galleries/:id/:title-view.html' => 'galleries#show', :as => :picture_view
  match 'create_gallery_comment/:id' => 'galleries#create_comment', :as => :picture_comment
  match 'home' => 'homes#index', :as => :home
  match 'comment_create_events' => 'events#create_comment', :as => :comment_create_events
    
  match 'request_information' => 'request_information#index', :as => :request 
  match 'sendmail' => 'request_information#sendmail'

  match '/manager/index_home' => 'manager#index_home', :as => :manager_index_home
  match '/manager/:id/update_home' => 'manager#update_home', :as => :manager_update_home
  match '/manager/create_home' => 'manager#create_home', :as => :manager_create_home
  match '/manager/:id/edit_home' => 'manager#edit_home', :as => :manager_edit_home
  match '/manager/new_home' => 'manager#new_home', :as => :manager_new_home
  match '/manager/:id/destroy_home' => 'manager#destroy_home', :as => :manager_destroy_home

  match '/manager/index_blog' => 'manager#index_blog', :as => :manager_index_blog
  match '/manager/:id/update_blog' => 'manager#update_blog', :as => :manager_update_blog
  match '/manager/create_blog' => 'manager#create_blog', :as => :manager_create_blog
  match '/manager/:id/edit_blog' => 'manager#edit_blog', :as => :manager_edit_blog
  match '/manager/new_blog' => 'manager#new_blog', :as => :manager_new_blog
  match '/manager/:id/destroy_blog' => 'manager#destroy_blog', :as => :manager_destroy_blog
  
  match '/manager/index_gallery' => 'manager#index_gallery', :as => :manager_index_gallery
  match '/manager/:id/update_gallery' => 'manager#update_gallery', :as => :manager_update_gallery
  match '/manager/create_gallery' => 'manager#create_gallery', :as => :manager_create_gallery
  match '/manager/:id/edit_gallery' => 'manager#edit_gallery', :as => :manager_edit_gallery
  match '/manager/new_gallery' => 'manager#new_gallery', :as => :manager_new_gallery
  match '/manager/:id/destroy_gallery' => 'manager#destroy_gallery', :as => :manager_destroy_gallery
  
  match '/manager/index_gallery_sections' => 'manager#index_gallery_sections', :as => :manager_index_gallery_sections
  match '/manager/:id/update_gallery_sections' => 'manager#update_gallery_sections', :as => :manager_update_gallery_sections
  match '/manager/create_gallery_sections' => 'manager#create_gallery_sections', :as => :manager_create_gallery_sections
  match '/manager/:id/edit_gallery_sections' => 'manager#edit_gallery_sections', :as => :manager_edit_gallery_sections
  match '/manager/new_gallery_sections' => 'manager#new_gallery_sections', :as => :manager_new_gallery_sections
  match '/manager/:id/destroy_gallery_sections' => 'manager#destroy_gallery_sections', :as => :manager_destroy_gallery_sections
  
  match '/manager/index_blog_categories' => 'manager#index_blog_categories', :as => :manager_index_blog_categories
  match '/manager/:id/update_blog_categories' => 'manager#update_blog_categories', :as => :manager_update_blog_categories
  match '/manager/create_blog_categories' => 'manager#create_blog_categories', :as => :manager_create_blog_categories
  match '/manager/:id/edit_blog_categories' => 'manager#edit_blog_categories', :as => :manager_edit_blog_categories
  match '/manager/new_blog_categories' => 'manager#new_blog_categories', :as => :manager_new_blog_categories
  match '/manager/:id/destroy_blog_categories' => 'manager#destroy_blog_categories', :as => :manager_destroy_blog_categories
  
  match '/manager/index_events' => 'manager#index_events', :as => :manager_index_events
  match '/manager/:id/update_events' => 'manager#update_events', :as => :manager_update_events
  match '/manager/create_events' => 'manager#create_events', :as => :manager_create_events
  match '/manager/:id/edit_events' => 'manager#edit_events', :as => :manager_edit_events
  match '/manager/new_events' => 'manager#new_events', :as => :manager_new_events
  match '/manager/:id/destroy_events' => 'manager#destroy_events', :as => :manager_destroy_events
  
  match '/manager/index_services' => 'manager#index_services', :as => :manager_index_services
  match '/manager/:id/update_services' => 'manager#update_services', :as => :manager_update_services
  match '/manager/create_services' => 'manager#create_services', :as => :manager_create_services
  match '/manager/:id/edit_services' => 'manager#edit_services', :as => :manager_edit_services
  match '/manager/new_services' => 'manager#new_services', :as => :manager_new_services
  match '/manager/:id/destroy_services' => 'manager#destroy_services', :as => :manager_destroy_services
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'register' => 'users#new', :as => :register
  
  match 'comments/:id/remove_comment_blog/:blog_id' => 'comments#remove_comment_blog', :as => :remove_comment_blog
  match 'comments/:id/remove_comment_gallery/:blog_id' => 'comments#remove_comment_gallery', :as => :remove_comment_gallery
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :email
	validates_presence_of :comment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save && simple_captcha_valid?
        format.html { redirect_to(blog_view_path(@comment.blog_id), :notice => 'Comment was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def remove_comment_blog
    @comment = Comment.find(params[:id])
    blog_id = params[:blog_id]
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(blog_view_url(blog_id)) }
    end
  end
  
 def remove_comment_gallery
    @comment = Comment.find(params[:id])
    blog_id = params[:blog_id]
    blog_id = blog_id.to_s.gsub('1212','')
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(picture_view_url(blog_id)) }
    end
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div id="new-comments">
	<div id="new-comments-header">
		Post a comment
	</div>
	<%= form_for @comment, :url => { :action => :create_comment } do |f| %>
	  <% if @comment.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
	
	      <ul>
	      <% @comment.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
	  <div class="field">
	    <%= f.label :name %><br />
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :email %><br />
	    <%= f.text_field :email %>
	  </div>
	  <div class="field">
	    <%= f.label :website %><br />
	    <%= f.text_field :website %>
	  </div>
	  <div class="field">
	    <%= f.label :comment %><br />
	    <%= f.text_area :comment %>
	    <p id="charlimitinfo"></p>
	  </div>
	  <input type="hidden" name="comment[blog_id]" value="<%= @blog.id %>">
	  
	  <div class="actions left clear mart10">
	    <%= f.submit "Post" %>
	  </div>
	<% end %>
</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Website</th>
    <th>Comment</th>
    <th>Blog</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.email %></td>
    <td><%= comment.website %></td>
    <td><%= comment.comment %></td>
    <td><%= comment.blog_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Email:</b>
  <%= @comment.email %>
</p>

<p>
  <b>Website:</b>
  <%= @comment.website %>
</p>

<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>

<p>
  <b>Blog:</b>
  <%= @comment.blog_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/view_comment.html.erb
<div id="comments-header" class="marb10">
	<button id="post-comments">Post a comment</button>
	<% if @comments.count > 0 %>
		<div id="view-comments-count">View comments (<%= @comments.count %>)</div>
	<% end %>
	<div class="clear"></div>
</div>

<% @comments.each do |comment| %>
  <fieldset class="comment clear">
  	<% if comment.website.empty? %>
  		<legend><%= comment.name %> <strong>Says:</strong></legend>
  	<% else %>
  		<legend><%= link_to comment.name, comment.website %> <strong>Says:</strong></legend>
  	<% end %>
  	<% if current_user %>
  	  	<%= link_to image_tag("close-button.png", :border => 0), remove_comment_blog_path(comment.id,comment.blog_id), :border => 0, :class => "right", :method => :delete %>	
  	<% end %>
    <p class="comment-body"><%= comment.comment %></p>
    <p class="info"><%= comment.created_at.strftime("%B %d %Y at %I:%M %p") %> </p>
  </fieldset>
<% end %>
<div id="paginate-style">
	<%= will_paginate @comments %>
</div>