config/routes.rb
Somethingchic::Application.routes.draw do

  resources :blogs, :comments, :users, :user_sessions, :homes, :galleries, :request_information, :users, :user_sessions, :gallery_sections, :services, :events
  
  root :to => 'homes#index'
  
  match 'create_comment/:id' => 'blogs#create_comment', :as => :comment_create
  match 'comments/:id/new_comment' => 'comments#new_comment', :as => :comment
  match 'blogs/:id/show-:title.html' => 'blogs#show', :as => :blog_view
  match 'blogs' => 'blogs#index', :as => :blog_home
  match 'events/:id/show-:title.html' => 'events#show', :as => :event_view
  match 'events' => 'events#index', :as => :event_home
  match 'services' => 'services#index', :as => :service_home
  match 'blog_categories/:id/:title-index.html' => 'blog_categories#show', :as => :blogs_by_name
  match 'galleries/:id/:title-index.html' => 'galleries#index', :as => :gallery_view
  match 'gallery_sections' => 'gallery_sections#index', :as => :gallery_section_index
  match 'galleries/:id/:title-view.html' => 'galleries#show', :as => :picture_view
  match 'create_gallery_comment/:id' => 'galleries#create_comment', :as => :picture_comment
  match 'home' => 'homes#index', :as => :home
  match 'comment_create_events' => 'events#create_comment', :as => :comment_create_events
    
  match 'request_information' => 'request_information#index', :as => :request 
  match 'sendmail' => 'request_information#sendmail'

  match '/manager/index_home' => 'manager#index_home', :as => :manager_index_home
  match '/manager/:id/update_home' => 'manager#update_home', :as => :manager_update_home
  match '/manager/create_home' => 'manager#create_home', :as => :manager_create_home
  match '/manager/:id/edit_home' => 'manager#edit_home', :as => :manager_edit_home
  match '/manager/new_home' => 'manager#new_home', :as => :manager_new_home
  match '/manager/:id/destroy_home' => 'manager#destroy_home', :as => :manager_destroy_home

  match '/manager/index_blog' => 'manager#index_blog', :as => :manager_index_blog
  match '/manager/:id/update_blog' => 'manager#update_blog', :as => :manager_update_blog
  match '/manager/create_blog' => 'manager#create_blog', :as => :manager_create_blog
  match '/manager/:id/edit_blog' => 'manager#edit_blog', :as => :manager_edit_blog
  match '/manager/new_blog' => 'manager#new_blog', :as => :manager_new_blog
  match '/manager/:id/destroy_blog' => 'manager#destroy_blog', :as => :manager_destroy_blog
  
  match '/manager/index_gallery' => 'manager#index_gallery', :as => :manager_index_gallery
  match '/manager/:id/update_gallery' => 'manager#update_gallery', :as => :manager_update_gallery
  match '/manager/create_gallery' => 'manager#create_gallery', :as => :manager_create_gallery
  match '/manager/:id/edit_gallery' => 'manager#edit_gallery', :as => :manager_edit_gallery
  match '/manager/new_gallery' => 'manager#new_gallery', :as => :manager_new_gallery
  match '/manager/:id/destroy_gallery' => 'manager#destroy_gallery', :as => :manager_destroy_gallery
  
  match '/manager/index_gallery_sections' => 'manager#index_gallery_sections', :as => :manager_index_gallery_sections
  match '/manager/:id/update_gallery_sections' => 'manager#update_gallery_sections', :as => :manager_update_gallery_sections
  match '/manager/create_gallery_sections' => 'manager#create_gallery_sections', :as => :manager_create_gallery_sections
  match '/manager/:id/edit_gallery_sections' => 'manager#edit_gallery_sections', :as => :manager_edit_gallery_sections
  match '/manager/new_gallery_sections' => 'manager#new_gallery_sections', :as => :manager_new_gallery_sections
  match '/manager/:id/destroy_gallery_sections' => 'manager#destroy_gallery_sections', :as => :manager_destroy_gallery_sections
  
  match '/manager/index_blog_categories' => 'manager#index_blog_categories', :as => :manager_index_blog_categories
  match '/manager/:id/update_blog_categories' => 'manager#update_blog_categories', :as => :manager_update_blog_categories
  match '/manager/create_blog_categories' => 'manager#create_blog_categories', :as => :manager_create_blog_categories
  match '/manager/:id/edit_blog_categories' => 'manager#edit_blog_categories', :as => :manager_edit_blog_categories
  match '/manager/new_blog_categories' => 'manager#new_blog_categories', :as => :manager_new_blog_categories
  match '/manager/:id/destroy_blog_categories' => 'manager#destroy_blog_categories', :as => :manager_destroy_blog_categories
  
  match '/manager/index_events' => 'manager#index_events', :as => :manager_index_events
  match '/manager/:id/update_events' => 'manager#update_events', :as => :manager_update_events
  match '/manager/create_events' => 'manager#create_events', :as => :manager_create_events
  match '/manager/:id/edit_events' => 'manager#edit_events', :as => :manager_edit_events
  match '/manager/new_events' => 'manager#new_events', :as => :manager_new_events
  match '/manager/:id/destroy_events' => 'manager#destroy_events', :as => :manager_destroy_events
  
  match '/manager/index_services' => 'manager#index_services', :as => :manager_index_services
  match '/manager/:id/update_services' => 'manager#update_services', :as => :manager_update_services
  match '/manager/create_services' => 'manager#create_services', :as => :manager_create_services
  match '/manager/:id/edit_services' => 'manager#edit_services', :as => :manager_edit_services
  match '/manager/new_services' => 'manager#new_services', :as => :manager_new_services
  match '/manager/:id/destroy_services' => 'manager#destroy_services', :as => :manager_destroy_services
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'register' => 'users#new', :as => :register
  
  match 'comments/:id/remove_comment_blog/:blog_id' => 'comments#remove_comment_blog', :as => :remove_comment_blog
  match 'comments/:id/remove_comment_gallery/:blog_id' => 'comments#remove_comment_gallery', :as => :remove_comment_gallery
  

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  layout "event"

  def index
    @events = Event.all
    @events = @events.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  def show
    @event = Event.find(params[:id])
    @comment = Comment.new
    @blogs = Blog.find(:all, :conditions => ["category_id=?", @event.blog_category_id ], :limit => 2 )
    @galleries = Gallery.find(:all, :conditions => ["gallery_id=?", @event.gallery_section_id ], :limit => 4, :order => "RAND()" )
    @comments = Comment.find(:all, :conditions => ["blog_id=?", @event.id ], :limit => 4 )
    @comments = @comments.paginate(:page => params[:page], :per_page => 5)
    render :layout => "event_details"
  end
  
  def create_comment
    @comment = Comment.new(params[:comment])
    @blog = Blog.find(@comment.blog_id)    

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(event_view_path(@comment.blog_id,@blog.title), :notice => 'Comment was successfully created.') }
      else
        format.html { render :action => "show" }
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_blog.html.erb
<div id="blog-container">
	<% @blogs.each do |blog| %>
		<% @comment = Comment.find(:all, :conditions => [ "blog_id=?", blog.id ]) %>
		<div class="clear marb20">
		<div id="blog-header">
			<div class="blog-date">
			  <div class='blog-month'><%= blog.created_at.strftime("%b") %></div>
			  <div class='blog-day'><%= blog.created_at.strftime("%e") %></div>
		  	</div>
		  	<div class="left">
		  		<%= link_to truncate( blog.title, :length => 37), blog_view_path(blog, :title => blog.title.gsub(/\s/,"-").gsub("\"","")), :class => "blog-title" %>
		  		<% if @comment.count > 0 %>
		  			<span class="comment-count"><%= @comment.count %> commet<% if !@comment.count.equal? 1 %>s<% end %></span>
		  		<% end %>
		  	</div>
		  	<div class="clear"></div>
		</div><!-- End blog-header -->
		
		<% if blog.photo.exists? then %>
			<%= image_tag blog.photo.url(:small), :id => "blog-image" %>
		<% end %>
		
		<div id="blog-body">
		  <%= truncate( blog.body.gsub(/<.*?>/, "") , :length => 250 ) %>
		  <%= link_to "read more", blog %><br/>
		</div>
		<div class="clear"></div>
	</div>
	<% end %>
	<div class="clear">Go to: <a href="/blog_categories/<%= @event.blog_category_id %>/<%= get_blog_category :blog_category_id => @event.blog_category_id %>-index.html"><%= get_blog_category :blog_category_id => @event.blog_category_id %></a></div>
	</div>

app/views/events/_comment_form.html.erb
<div id="new-comments">
	<div id="new-comments-header">
		Post a comment
	</div>
	<%= form_tag comment_create_events_path, :method => :post do  %>

	
	  <div class="field">
	    <label for="name">Name</label><br />
	    <input type="text" name="comment[name]" id="name">
	  </div>
	  <div class="field">
	    <label for="email">Email</label><br />
	    <input type="text" name="comment[email]" id="email">
	  </div>
	  <div class="field">
	    <label for="website">Website</label><br />
	    <input type="text" name="comment[website]" id="website">
	  </div>
	  <div class="field">
	    <label for="comment">Comment</label><br />
	    <textarea name="comment[comment]" id="comment"></textarea>
	    <p id="charlimitinfo"></p>
	  </div>
	  <input type="hidden" name="comment[blog_id]" value="<%= @event.id %>">
	  
	  <div class="actions left clear mart10">
	    <%= submit_tag "Post" %>
	  </div>
	<% end %>
</div>

app/views/events/_gallery.html.erb
<div id="gallery-container">
	<div class="gallery clearfix">
		<% @galleries.each do |gallery| %>
			<div class="gallery-img">
				<div class="left"><img src="<%= gallery.photo.url(:thumb) %>" width="175" height="175" alt="<%= gallery.title %>" /></div>
				<div class="clear"></div>
			</div>
		<% end %>
	</div>
	<div class="clear">Go to: <a href="/galleries/<%= @event.gallery_section_id %>/<%= get_gallery_section :category_id => @event.gallery_section_id %>-index.html"><%= get_gallery_section :category_id => @event.gallery_section_id %></a></div>
</div>

app/views/events/_view_comment.html.erb
<% @comments.each do |comment| %>
  <fieldset class="comment clear">
  	<% if comment.website.empty? %>
  		<legend><%= comment.name %> <strong>Says:</strong></legend>
  	<% else %>
  		<legend><%= link_to comment.name, comment.website %> <strong>Says:</strong></legend>
  	<% end %>
  	<% if current_user %>
  	  	<%= link_to image_tag("close-button.png", :border => 0), remove_comment_blog_path(comment.id,comment.blog_id), :border => 0, :class => "right", :method => :delete %>	
  	<% end %>
    <p class="comment-body"><%= comment.comment %></p>
    <p class="info"><%= comment.created_at.strftime("%B %d %Y at %I:%M %p") %> </p>
  </fieldset>
<% end %>
<div id="paginate-style">
	<%= will_paginate @comments %>
</div>

app/views/events/index.html.erb
<div id="main">
		   	
	<ul class="gallery clearfix">
	<% @events.each do |event| %>
		<li class="marb10 clear">
			<div class="left"><img src="<%= event.price %>" width="175" height="175" /></div>
			<div id="info">
				<%= link_to event.title, event_view_path(event.id, :title => event.title.gsub(/\s/,"-").gsub("\"","")) %>
				<p><%= event.description %></p>
			</div>
			<div class="clear"></div>
		</li>
	<% end %>
	<% if (@events.blank?) %>
		<div class="left clear mar10">
		  No events have been added yet.
		</div>
	<% end %>
		
	</ul>
			
</div>
	
<div id="paginate-style">
	<%= will_paginate @events %>
</div>

app/views/events/show.html.erb
<div class="left clear" style="width:920px;">
	<div class="left" style="width:500px;">
		<div class="marb20">
			<img src="<%= @event.price %>" class="left"/>
			<div class="left" style="width:295px; margin-left:15px; border:1px solid #999999; background-color:#D3D1D1; padding:5px;">
				<%= @event.description %>
			</div>
			<div class="clear"></div>
		</div>
		<%= render 'events/blog' %>
	</div>
	
	<div class="left" style="text-align:right; width:410px;">
	  <span style="margin-bottom:20px; font-size: 27px; font-weight: normal; letter-spacing: -0.03em; line-height: 1em;font-family: 'Trebuchet MS',Arial,Helvetica,sans-serif; color:#669999;"><em><%= @event.title %></em></span>
	  	<%= render 'events/gallery' %>
	  	<div id="comments-header" class="marb10">
			<button id="post-comments">Post a comment</button>
			<div class="clear"></div>
		</div>
	  	<div id="add-comments" class="clear" style="display:none; text-align:left;">
			<%= render :partial => 'events/comment_form' %>
		</div>
		<div id="view-comments" class="clear">
			<%= render :partial => 'events/view_comment' %>
		</div>
	</div>
</div>